Question 1:
Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [1]:
import numpy as np
x = np.array([3, 5])
y = np.array([2, 5])
print("Original numbers:")
print(x)
print(y)
#"Comparison greater"
print(np.greater(x, y))
#"Comparison greater equal"
print(np.greater_equal(x, y))
#"Comparison less"
print(np.less(x, y))
#Comparison less equal
print(np.less_equal(x, y))

Original numbers:
[3 5]
[2 5]
[ True False]
[ True  True]
[False False]
[False  True]


Question 2:
Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [5]:
array=np.zeros(10)
#An array of 10 zeros
print(array)
array=np.ones(10)
#An array of 10 ones
print(array)
array=np.ones(10)*5
#An array of 10 fives
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


Question 3:
Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a
given array

In [6]:
x = np.array([[0,9],[5,3]])
#Original array
print(x)
#Sum of all elements
print(np.sum(x))
#Sum of each column
print(np.sum(x, axis=0))
#Sum of each row
print(np.sum(x, axis=1))

[[0 9]
 [5 3]]
17
[ 5 12]
[9 8]


Question 4:
Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [7]:
#Add
print(np.add(1.0, 5.0))
#Subtract
print(np.subtract(6.0, 9.0))
#Multiply
print(np.multiply(12.0, 4.0))
#Divide
print(np.divide(16.0, 41.0))

6.0
-3.0
48.0
0.3902439024390244


Question 5:
Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in
degree.

In [8]:
#sine: array of angles given in degrees
print(np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
#cosine: array of angles given in degrees
print(np.cos(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
#tangent: array of angles given in degrees
print(np.tan(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))

[0.         0.5        0.70710678 0.8660254  1.        ]
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


Question 6:
Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the
index labels

In [8]:
import pandas as pd
data={'virat':[40,45,67,89,100,150],'Rohit':[2,7,9,100,50,43]}
data
df=pd.DataFrame(data,index=['day1','day2','day3','day4','day5','day6'])
df

virat  Rohit
day1     40      2
day2     45      7
day3     67      9
day4     89    100
day5    100     50
day6    150     43

Question 7:
Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.

In [11]:
df.iloc[1]

virat    45
Rohit     7
Name: day2, dtype: int64

In [12]:
df.loc['day1']

virat    40
Rohit     2
Name: day1, dtype: int64

Question 8:
Write a Pandas program to join the two given dataframes along rows and assign all data.

In [15]:
data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'], 
        'Age':[27, 24, 22, 32], 
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'], 
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']} 

data2 = {'Name':['Abhi', 'Ayushi', 'Dhiraj', 'Hitesh'], 
        'Age':[17, 14, 12, 52], 
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'], 
        'Qualification':['Btech', 'B.A', 'Bcom', 'B.hons']} 
df=pd.DataFrame(data1)
df1=pd.DataFrame(data2)
k=[df,df1]
result=pd.concat(k)
result

Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd
0    Abhi   17     Nagpur         Btech
1  Ayushi   14     Kanpur           B.A
2  Dhiraj   12  Allahabad          Bcom
3  Hitesh   52    Kannuaj        B.hons

In [20]:
data1 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'key1': ['K0', 'K1', 'K0', 'K1'],
         'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'], 
        'Age':[27, 24, 22, 32],} 
   

data2 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'key1': ['K0', 'K0', 'K0', 'K0'],
         'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'], 
        'Qualification':['Btech', 'B.A', 'Bcom', 'B.hons']} 

df = pd.DataFrame(data1) 
df1 = pd.DataFrame(data2) 
res = pd.merge(df, df1, how='outer', on=['key', 'key1'])
 
res

key key1    Name   Age    Address Qualification
0  K0   K0     Jai  27.0     Nagpur         Btech
1  K1   K1  Princi  24.0        NaN           NaN
2  K2   K0  Gaurav  22.0  Allahabad          Bcom
3  K3   K1    Anuj  32.0        NaN           NaN
4  K1   K0     NaN   NaN     Kanpur           B.A
5  K3   K0     NaN   NaN    Kannuaj        B.hons

Question 9:
Write a Pandas program to detect missing values of a given DataFrame. Display True or False.

In [25]:
res.isna()

key   key1   Name    Age  Address  Qualification
0  False  False  False  False    False          False
1  False  False  False  False     True           True
2  False  False  False  False    False          False
3  False  False  False  False     True           True
4  False  False   True   True    False          False
5  False  False   True   True    False          False

In [27]:
df4 = pd.DataFrame({
'ord_no':[70001,np.nan,70002,70004,np.nan,70005,np.nan,70010,70003,70012,np.nan,70013],
'purch_amt':[150.5,270.65,65.26,110.5,948.5,2400.6,5760,1983.43,2480.4,250.45, 75.29,3045.6],
'ord_date': ['2012-10-05','2012-09-10',np.nan,'2012-08-17','2012-09-10','2012-07-27','2012-09-10','2012-10-10','2012-10-10','2012-06-27','2012-08-17','2012-04-25'],
'customer_id':[3002,3001,3001,3003,3002,3001,3001,3004,3003,3002,3001,3001],
'salesman_id':[5002,5003,5001,np.nan,5002,5001,5001,np.nan,5003,5002,5003,np.nan]})
print(df4)
print(df4.isna())

     ord_no  purch_amt    ord_date  customer_id  salesman_id
0   70001.0     150.50  2012-10-05         3002       5002.0
1       NaN     270.65  2012-09-10         3001       5003.0
2   70002.0      65.26         NaN         3001       5001.0
3   70004.0     110.50  2012-08-17         3003          NaN
4       NaN     948.50  2012-09-10         3002       5002.0
5   70005.0    2400.60  2012-07-27         3001       5001.0
6       NaN    5760.00  2012-09-10         3001       5001.0
7   70010.0    1983.43  2012-10-10         3004          NaN
8   70003.0    2480.40  2012-10-10         3003       5003.0
9   70012.0     250.45  2012-06-27         3002       5002.0
10      NaN      75.29  2012-08-17         3001       5003.0
11  70013.0    3045.60  2012-04-25         3001          NaN
    ord_no  purch_amt  ord_date  customer_id  salesman_id
0    False      False     False        False        False
1     True      False     False        False        False
2    False      False      True  

Question 10:
Write a Pandas program to create and display a one-dimensional array-like object containing an array of
data.

In [26]:
s = pd.Series([2, 4, 6, 8, 10])
s

0     2
1     4
2     6
3     8
4    10
dtype: int64