Question 1:
Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [1]:
import numpy as np
x = np.array([3, 5])
y = np.array([2, 5])
print("Original numbers:")
print(x)
print(y)
#"Comparison greater"
print(np.greater(x, y))
#"Comparison greater equal"
print(np.greater_equal(x, y))
#"Comparison less"
print(np.less(x, y))
#Comparison less equal
print(np.less_equal(x, y))

Original numbers:
[3 5]
[2 5]
[ True False]
[ True  True]
[False False]
[False  True]


Question 2:
Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [5]:
array=np.zeros(10)
#An array of 10 zeros
print(array)
array=np.ones(10)
#An array of 10 ones
print(array)
array=np.ones(10)*5
#An array of 10 fives
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


Question 3:
Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a
given array

In [6]:
x = np.array([[0,9],[5,3]])
#Original array
print(x)
#Sum of all elements
print(np.sum(x))
#Sum of each column
print(np.sum(x, axis=0))
#Sum of each row
print(np.sum(x, axis=1))

[[0 9]
 [5 3]]
17
[ 5 12]
[9 8]


Question 4:
Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [7]:
#Add
print(np.add(1.0, 5.0))
#Subtract
print(np.subtract(6.0, 9.0))
#Multiply
print(np.multiply(12.0, 4.0))
#Divide
print(np.divide(16.0, 41.0))

6.0
-3.0
48.0
0.3902439024390244


Question 5:
Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in
degree.

In [8]:
#sine: array of angles given in degrees
print(np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
#cosine: array of angles given in degrees
print(np.cos(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
#tangent: array of angles given in degrees
print(np.tan(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))

[0.         0.5        0.70710678 0.8660254  1.        ]
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


we didnt entered pandas